[ADOdb]
directory=c:/dev/github/ADOdb
;0 ADODB_ASSOC_CASE_LOWER
;1 ADODB_ASSOC_CASE_UPPER
;2 ADODB_ASSOC_CASE_NATIVE
casing=1;
;ADODB_FORCE_IGNORE',0
;ADODB_FORCE_NULL',1
;ADODB_FORCE_EMPTY',2
;ADODB_FORCE_VALUE',3
;ADODB_FORCE_NULL_AND_ZERO',4
forcemode=0;


[blob]
testBlob=/opt/var/tests/unittest.jpg

[globals]
date.timezone = 'America/Denver'

[caching]
cacheMethod=0
cacheDir=c:/dev/cache
cacheHost = 192.168.1.50

[meta]
skipDbCreation=1

[xmlschema]
skipXmlTests=0
debug=0

[activerecord]
skipTests=0
extended=0

[storedprocedures]
skipTests=1;

[SQLite3]
driver=sqlite3
dsn=/opt/var/tests/unittest.db
;dsn=:memory:
active=0
debug=0

[MySQL 9]
driver=mysqli
dsn=
host=mysql9.local
user=unittest
password="unittest"
database=testdb
debug=0
parameters="7=utf8mb4;"
active=0

[MySQL 8]
driver=mysqli
dsn=
host=mysql8.local
user=unittest
password="unittest"
database=unittest
debug=0
parameters="7=utf8mb4;"
active=0

[pdo-mysql]
driver=pdo-mysql
dsn="host=mysql.local;database=tester;username=unittest;password='unittest'"
host=mysql8.local
user=root
password="Adg4ever!"
database=employees
debug=0
;parameters="7=utf8mb4;"
active=0

[PGSql]
driver=postgres9
dsn=
host=postgres.local
user=postgres
password=postgres
database=unittest
active=0
debug=0

[SQL Server]
driver=mssqlnative
dsn=0
host=mssqlserver.local
user=sa
password="microsoft"
database=unittest
parameters="LoginTimeout=60;TrustServerCertificate=1;"
debug=1
active=0

[pdo-sqlite]
driver=pdo-sqlite
dsn=:memory:
debug=0;

[IBM DB2]
driver=db2
dsn='hostname=db2.local;protocol=tcpip;port=25010;database=TEST;uid=db2;pwd=db2';
debug=1
active=0
