-- Firebird Test tables for the active record module


RECREATE TABLE persons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name_first VARCHAR(100) NOT NULL,
    name_last VARCHAR(100) NOT NULL,
    birth_date DATE,
    PRIMARY KEY  (id)
);

RECREATE TABLE children (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    person_id INT NOT NULL,
    name_first VARCHAR(100) NOT NULL,
    name_last VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    PRIMARY KEY (id)
);