-- Standard format for testing autoexecute based functions
-- used by all the test in /Helpers
RECREATE TABLE AUTOEXECUTE (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	varchar_field VARCHAR(20),
	date_field DATE DEFAULT CURRENT_DATE,
	integer_field SMALLINT DEFAULT 0,
	decimal_field DECIMAL(12,2) DEFAULT 0,
    empty_field VARCHAR(240) DEFAULT '',
	number_run_field INTEGER DEFAULT 0,
	PRIMARY KEY (id)
);

RECREATE SEQUENCE autoexecute_seq;

-- READ <<
CREATE TRIGGER autoexecute_trigger FOR autoexecute
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.id IS NULL) THEN
        NEW.id = NEXT VALUE FOR autoexecute_seq;
END;
-- <<
