-- Standard format for testing autoexecute based functions
-- used by all the test in /Helpers
-- DROP TABLE AUTOEXECUTE;

RECREATE TABLE AUTOEXECUTE (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	varchar_field VARCHAR(20),
	date_field DATE DEFAULT CURRENT_DATE,
	integer_field SMALLINT DEFAULT 0,
	decimal_field DECIMAL(12,2) DEFAULT 0,
    empty_field VARCHAR(240) DEFAULT '',
	number_run_field INTEGER DEFAULT 0,
	decimal_eval_field DECIMAL(12,4) DEFAULT 5.0000,
	varchar_eval_field BIGINT,
	PRIMARY KEY (id)
);
