
-- blob_storage_table is used to test blob storage

RECREATE TABLE blob_storage_table (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	integer_field INTEGER,
	blob_field BLOB,
	clob_field BLOB CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
	varchar_field VARCHAR(20)
);

