-- Acts as a test for manipulation of date variables

RECREATE TABLE date_columns_test (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	datetime_field DATETIME,
	date_field DATE,
	sqldate_test_field DATETIME,
	offsetdate_test_field DATETIME,
	PRIMARY KEY(id)
	
);
