-- This table is used to test changes to columns via dictionary
-- functions. not used by createTableSql
-- Reprocessed for each test to provide a standard baseline


-- Missing ENUM support until added to ADOdb
-- enum_field_to_keep ENUM('duplo','lego','meccano'),

RECREATE TABLE dictionary_change_test_table (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

	date_field DATE  DEFAULT '2030-01-01',
	integer_field SMALLINT DEFAULT 0,
	decimal_field_to_modify DECIMAL(8,4) DEFAULT 0,
	boolean_field_to_rename BOOLEAN DEFAULT 0,
	boolean_field_to_change_default BOOLEAN DEFAULT 1,
    droppable_field DECIMAL(10,6) DEFAULT 80.111,
	varchar_field VARCHAR(50) DEFAULT '',
	nvarchar_field VARCHAR(50) DEFAULT '',
	smallint_to_expand SMALLINT,
	xl_field BLOB,
	PRIMARY KEY(id)
);
CREATE UNIQUE INDEX index_to_drop ON dictionary_change_test_table (varchar_field);