-- Foreign keys test suite for IBM DB2 driver
-- No data is loaded into these tables

-- Must drop foreign_key_target_1 and 2 before foreign_key_source because of foreign key constraints


-- Creates a first foreign reference for foreign_key_source

-- PRINT DROP foreign_key_source

RECREATE TABLE foreign_key_source (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	integer_field SMALLINT DEFAULT 0 NOT NULL,
	tt_id_1 INTEGER NOT NULL,
	tt_id_2 INTEGER NOT NULL,
	PRIMARY KEY (id)
);

-- PRINT DROP foreign_key_target_1

RECREATE TABLE foreign_key_target_1 (
	id_1 INTEGER GENERATED BY DEFAULT AS IDENTITY,
	integer_field_1 SMALLINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (id_1,integer_field_1)
);

-- PRINT DROP foreign_key_target_2

-- Creates a second foreign reference for foreign_key_source
RECREATE TABLE foreign_key_target_2 (
	id_2 INTEGER GENERATED BY DEFAULT AS IDENTITY,
	integer_field_2 SMALLINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (id_2,integer_field_2)
);

-- foreign_key_source links to constraints above



CREATE UNIQUE INDEX fks ON foreign_key_source (integer_field);

-- PRINT Adding Foreign Key to foreign_key_target_1

ALTER TABLE foreign_key_source
ADD FOREIGN KEY (tt_id_1,integer_field)
	REFERENCES foreign_key_target_1(id_1,integer_field_1);


-- PRINT Adding Foreign Key to foreign_key_target_2

ALTER TABLE foreign_key_source
ADD FOREIGN KEY (tt_id_2,integer_field)
	REFERENCES foreign_key_target_2(id_2,integer_field_2);