-- length-test is loaded with 20 character defaults for testing the length functions

RECREATE TABLE length_test (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    char_field CHAR(30) DEFAULT 'TEST567890TEST567890',
    varchar_field VARCHAR(30) DEFAULT 'TEST567890TEST567890'
);




-- PRINT Insert

--INSERT INTO length_test (id, char_field, varchar_field) VALUES (1, 'TEST567890TEST567890','TEST567890TEST567890');

-- PRINT done inserting
