
-- This table is used to test the quoting of table and field names
-- It uses a reserved word as the table name and column names

RECREATE TABLE "table_name" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"column_name" VARCHAR(20)
);