-- Standard format for the unit testing
DROP VIEW TESTTABLE_1_VIEW;
-- All drivers must have the same table and column structure
-- so that all tests run the same way
-- but this is native inserts so the column types may differ across databases
-- PRINT Loading Testtable_1
-- Testtable_1 is used to test the basic functionality of the meta functions
-- It has a variety of data types but contains no data
RECREATE TABLE TESTTABLE_1 (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	varchar_field VARCHAR(20),
	datetime_field TIMESTAMP,
	date_field DATE DEFAULT CURRENT_DATE,
	integer_field SMALLINT DEFAULT 0,
	decimal_field DECIMAL(12,2) DEFAULT 0,
	boolean_field BOOLEAN DEFAULT 0,
    empty_field VARCHAR(240) DEFAULT '',
	number_run_field INTEGER DEFAULT 0,
	PRIMARY KEY (id,integer_field)
);
-- PRINT Load additional indexes
CREATE	UNIQUE INDEX vdx1 ON testtable_1 (varchar_field);
CREATE	UNIQUE INDEX vdx2 ON testtable_1 (integer_field,date_field);
CREATE	UNIQUE INDEX vdx3 ON testtable_1 (number_run_field);

-- 2. Create a sequence (generator)
RECREATE SEQUENCE testtable_1_seq;

-- 3. Create a BEFORE INSERT trigger to auto-generate IDs
-- SET TERM !! ; 
-- READ <<
CREATE TRIGGER testtable_1_trigger FOR testtable_1
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.id IS NULL) THEN
        NEW.id = NEXT VALUE FOR testtable_1_seq;
END;
-- <<

-- PRINT Load testtable_1_view
-- Simple View onto testtable 1
CREATE VIEW testtable_1_view AS 
	SELECT id,varchar_field
	FROM testtable_1
	WHERE varchar_field IS NOT NULL;

-- PRINT Load testtable_3
-- Testtable_3 is loaded with data for testing the cache and sql functions
RECREATE TABLE testtable_3 (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	varchar_field VARCHAR(20),
	datetime_field TIMESTAMP,
	date_field DATE DEFAULT CURRENT_DATE,
	integer_field SMALLINT DEFAULT 0,
	decimal_field DECIMAL(12,2) DEFAULT 0,
	boolean_field BOOLEAN DEFAULT 0,
    empty_field VARCHAR(240) DEFAULT '',
	number_run_field INTEGER DEFAULT 0,
	PRIMARY KEY (id,integer_field)
);
CREATE	UNIQUE INDEX vdx31 ON testtable_3 (varchar_field);
CREATE	UNIQUE INDEX vdx33 ON testtable_3 (number_run_field);

RECREATE SEQUENCE testtable_3_seq;
 
-- READ <<
CREATE TRIGGER testtable_3_trigger FOR testtable_3
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.id IS NULL) THEN
        NEW.id = NEXT VALUE FOR testtable_3_seq;
END;
-- <<
